### ISSUE TITLE
Bot doesn't start after checking frames.

### ISSUE THREAD

**Issue by Beteoto** [thecodingbob/framebot#4] opened 2021-07-20 20:59 UTC
![image](https://user-images.githubusercontent.com/67559786/126394520-b0f37dac-a7da-4947-a228-b8b7aa47dae7.png)

Hi, i was having the issue of "0 Frames found", after deleting the quotes from the config.ini it says this.

**Comment by nicholasfreed** [comment] 2021-08-04 18:03
You should name the frames without the 'frame' prefix (e.g.: 01948.jpg), otherwise the bot won't be able to extract the frame number for each file. This is expected in the current version of the bot, not a bug, so I'm closing the issue.

**Closed as completed by nicholasfreed** 2021-08-04 18:03 UTC
